### ISSUE TITLE
A task is assigned automatically only when creating a new task

### ISSUE THREAD

**Issue by restovictor** [noneal/redmine_auto_assigned#2]
Hello! I have a problem. A task is assigned automatically only when creating a new task. If i changing the status from NEW to another, issue is not assigned to user, im must manually click on the "Remove current assignee" button, after this the assignment field is filled automatically from the script

![image](https://user-images.githubusercontent.com/49451181/55819203-ed3f7f80-5b00-11e9-9762-1194f106584b.png)

**Comment by noneal** [comment]
This plugin only auto assigns when the assigned to user is blank.

**Comment by restovictor** [comment]
can you create plugin with auto assignment from changing state?

**Comment by noneal** [comment]
That is not the purpose of this plugin. Feel free to fork this code and create your own modifications.
